// <auto-generated />
using Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Core.EntityModels.Boat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Length")
                        .HasColumnType("int");

                    b.Property<string>("Material")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Sail")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Boat");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "Red",
                            Length = 11,
                            Material = "İron",
                            Sail = false
                        },
                        new
                        {
                            Id = 2,
                            Color = "Red",
                            Length = 12,
                            Material = "Steel",
                            Sail = false
                        },
                        new
                        {
                            Id = 3,
                            Color = "White",
                            Length = 10,
                            Material = "Wooden",
                            Sail = true
                        },
                        new
                        {
                            Id = 4,
                            Color = "White",
                            Length = 13,
                            Material = "Carbon",
                            Sail = true
                        },
                        new
                        {
                            Id = 5,
                            Color = "White",
                            Length = 11,
                            Material = "Wooden",
                            Sail = true
                        },
                        new
                        {
                            Id = 6,
                            Color = "Black",
                            Length = 12,
                            Material = "İron",
                            Sail = false
                        },
                        new
                        {
                            Id = 7,
                            Color = "Black",
                            Length = 12,
                            Material = "Steel",
                            Sail = false
                        },
                        new
                        {
                            Id = 8,
                            Color = "Blue",
                            Length = 9,
                            Material = "İron",
                            Sail = false
                        });
                });

            modelBuilder.Entity("Core.EntityModels.Bus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Capasity")
                        .HasColumnType("int");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Length")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Bus");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capasity = 100,
                            Color = "Red",
                            Length = 11
                        },
                        new
                        {
                            Id = 2,
                            Capasity = 80,
                            Color = "Red",
                            Length = 12
                        },
                        new
                        {
                            Id = 3,
                            Capasity = 60,
                            Color = "White",
                            Length = 10
                        },
                        new
                        {
                            Id = 4,
                            Capasity = 100,
                            Color = "White",
                            Length = 13
                        },
                        new
                        {
                            Id = 5,
                            Capasity = 75,
                            Color = "White",
                            Length = 11
                        },
                        new
                        {
                            Id = 6,
                            Capasity = 90,
                            Color = "Black",
                            Length = 12
                        },
                        new
                        {
                            Id = 7,
                            Capasity = 85,
                            Color = "Black",
                            Length = 12
                        },
                        new
                        {
                            Id = 8,
                            Capasity = 69,
                            Color = "Blue",
                            Length = 9
                        });
                });

            modelBuilder.Entity("Core.EntityModels.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("HeadlightsState")
                        .HasColumnType("bit");

                    b.Property<int>("Model")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Car");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "Wolksvagen",
                            Color = "Red",
                            HeadlightsState = true,
                            Model = 2018
                        },
                        new
                        {
                            Id = 2,
                            Brand = "Ford",
                            Color = "Red",
                            HeadlightsState = true,
                            Model = 2017
                        },
                        new
                        {
                            Id = 3,
                            Brand = "Renault",
                            Color = "White",
                            HeadlightsState = false,
                            Model = 2014
                        },
                        new
                        {
                            Id = 4,
                            Brand = "Wolksvagen",
                            Color = "Blue",
                            HeadlightsState = true,
                            Model = 2020
                        },
                        new
                        {
                            Id = 5,
                            Brand = "Jaguar",
                            Color = "White",
                            HeadlightsState = false,
                            Model = 2018
                        },
                        new
                        {
                            Id = 6,
                            Brand = "Ferrari",
                            Color = "Black",
                            HeadlightsState = true,
                            Model = 2019
                        },
                        new
                        {
                            Id = 7,
                            Brand = "Skoda",
                            Color = "Black",
                            HeadlightsState = false,
                            Model = 2022
                        },
                        new
                        {
                            Id = 8,
                            Brand = "AlfaRomeo",
                            Color = "Blue",
                            HeadlightsState = true,
                            Model = 2021
                        });
                });

            modelBuilder.Entity("Core.EntityModels.Wheel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("BusId")
                        .HasColumnType("int");

                    b.Property<int>("CarId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BusId")
                        .IsUnique();

                    b.HasIndex("CarId")
                        .IsUnique();

                    b.ToTable("Wheel");
                });

            modelBuilder.Entity("Core.EntityModels.Wheel", b =>
                {
                    b.HasOne("Core.EntityModels.Bus", null)
                        .WithOne("Wheels")
                        .HasForeignKey("Core.EntityModels.Wheel", "BusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.EntityModels.Car", null)
                        .WithOne("Wheels")
                        .HasForeignKey("Core.EntityModels.Wheel", "CarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Core.EntityModels.Bus", b =>
                {
                    b.Navigation("Wheels")
                        .IsRequired();
                });

            modelBuilder.Entity("Core.EntityModels.Car", b =>
                {
                    b.Navigation("Wheels")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
